#!/bin/bash
# Usage:
#   download_spinnaker ARCH WORK_DIR UBUNTU_RELEASE

if [ "$#" != "3" ];
then
  echo "Usage:"
  echo "\t download_spinnaker ARCH WORK_DIR UBUNTU_RELEASE"
  exit 1
fi

ARCH=$1
WORK_DIR=$2
RELEASE=$3

if [ "$RELEASE" != "focal" ];
then
  echo "Wrong release; this script only works for Ubuntu 20.04 'focal'"
  exit 1
fi

case $ARCH in
  "x86_64")
    URL="https://packages.clearpathrobotics.com/stable/flir/Spinnaker/Ubuntu18.04/spinnaker-1.27.0.48-Ubuntu18.04-amd64-pkg.tar.gz"
    SPIN_DIR="spinnaker-1.27.0.48-amd64"
  ;;

  "i386")
    URL="https://packages.clearpathrobotics.com/stable/flir/Spinnaker/Ubuntu18.04/spinnaker-1.27.0.48-Ubuntu18.04-i386-pkg.tar.gz"
    SPIN_DIR="spinnaker-1.27.0.4-i386"
  ;;

  "armv7")
    URL="https://packages.clearpathrobotics.com/stable/flir/Spinnaker/Ubuntu18.04/spinnaker-1.27.0.48-Ubuntu18.04-armhf-pkg.tar.gz"
    SPIN_DIR="spinnaker-1.27.0.48-armhf"
  ;;

  "armv8")
    URL="https://packages.clearpathrobotics.com/stable/flir/Spinnaker/Ubuntu18.04/spinnaker-1.27.0.48-Ubuntu18.04-arm64-pkg.tar.gz"
    SPIN_DIR="spinnaker-1.27.0.48-arm64"
  ;;
esac

echo "Working directory: $WORK_DIR"
if [ ! -d $WORK_DIR ];
then
  echo "Working directory doesn't exit! making it"
  mkdir -p $WORK_DIR
fi
cd $WORK_DIR
echo $(pwd)

echo "Downloading libspinnaker from $URL"
wget $URL -O spinnaker.tar.gz

echo "Unpacking tarball"
tar xf spinnaker.tar.gz

echo "Installing packages"
cd $SPIN_DIR
sudo dpkg -i *.deb
sudo apt-get -f install
